name: Deploy Sphinx Docs to GitHub Pages

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx myst-parser pydata-sphinx-theme ghp-import

    - name: Build documentation
      run: |
        cd unravel/docs
        make html

    - name: Deploy to GitHub Pages
      run: |
        cd unravel/docs
        ghp-import -n -p -f _build/html
